name: 'Report Lighthouse'
description: 'report lighthouse stats for challenge-4'
inputs:
  lang:
    description: 'the programming language in use'
    required: true
    default: javascript
  server:  
    description: 'base API endpoint URL'
    required: true
    default: 'https://us-central1-buildforsdg.cloudfunctions.net'
runs:
  using: 'node12'
  main: 'dist/index.js'
